### ISSUE TITLE
海外用户无法绑定手机号

### ISSUE THREAD

**Issue by Jinqi-Cheng** [Mfweb/adao_member#2]
显示 错误[Auth] 
确认手机号是正确的
![0AB1FD63-60CE-4CBB-8E05-0FF742F0C853](https://user-images.githubusercontent.com/38298869/81673629-cb4db600-9400-11ea-97e7-b72a902ec43f.jpeg)

**Comment by Mfweb** [comment]
直接打开此链接看看有没有网络错误
https://reed.mfweb.top/nmb/Member/User/Authentication/mobileReverseAuthCode

**Comment by Jinqi-Cheng** [comment]
显示":( 并没有权限访问", 之后跳转有报错, 截图如下:
![image](https://user-images.githubusercontent.com/38298869/81774180-d6572380-949e-11ea-9f65-d71256a23496.png)

**Comment by Mfweb** [comment]
再试试认证是否还报错，最近岛服务器不太稳定，间隔一段时间试试，还不行的话麻烦加我微信MfwebN，远程调试一下

**Comment by Mfweb** [comment]
已解决，CDN问题
